name: Manage FUNDING.yml

on:
  issues:
    types: [opened, labeled]

jobs:
  create-funding-pr:
    if: contains(github.event.issue.labels.*.name, 'funding-yml-requested')
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
      contents: read
      
    steps:
      - name: Manage FUNDING.yml
        uses: oss-wishlist/manage-funding-yml@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
